-- ALPHA PLATFORM V3.7 — additive notification experience upgrade
-- Safe to run after upgrade-v3.6.sql. No existing tables or calculations are removed.
begin;

alter table public.recommendations add column if not exists send_push_notification boolean not null default true;
alter table public.strategy_months add column if not exists send_push_notification boolean not null default true;
alter table public.portfolios add column if not exists send_push_notification boolean not null default true;
alter table public.weekly_reports add column if not exists send_push_notification boolean not null default true;
alter table public.recommendation_updates add column if not exists send_push_notification boolean not null default true;

create table if not exists public.user_notification_inbox (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_id uuid not null references public.notification_events(id) on delete cascade,
  delivered_at timestamptz,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id, event_id)
);
create index if not exists user_notification_inbox_user_idx on public.user_notification_inbox(user_id, read_at, created_at desc);
alter table public.user_notification_inbox enable row level security;
drop policy if exists "members read own notification inbox" on public.user_notification_inbox;
create policy "members read own notification inbox" on public.user_notification_inbox for select to authenticated using (auth.uid() = user_id);
drop policy if exists "members update own notification inbox" on public.user_notification_inbox;
create policy "members update own notification inbox" on public.user_notification_inbox for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
grant select, update on public.user_notification_inbox to authenticated;

create or replace function public.mark_all_notifications_read()
returns integer language plpgsql security definer set search_path=public as $$
declare affected integer;
begin
  update public.user_notification_inbox set read_at = coalesce(read_at, now()) where user_id = auth.uid() and read_at is null;
  get diagnostics affected = row_count;
  return affected;
end; $$;
grant execute on function public.mark_all_notifications_read() to authenticated;

create or replace function public.queue_alpha_notification(
  p_event_type text,
  p_title text,
  p_body text,
  p_target_url text default '/dashboard',
  p_payload jsonb default '{}'::jsonb,
  p_dedupe_key text default null
) returns uuid language plpgsql security definer set search_path=public as $$
declare event_id uuid;
begin
  insert into public.notification_events(event_type,title,body,target_url,payload,dedupe_key)
  values(left(coalesce(p_event_type,'platform_update'),100),left(coalesce(p_title,'ALPHA CORE update'),180),left(coalesce(p_body,'A new update is available.'),500),left(coalesce(p_target_url,'/dashboard'),500),coalesce(p_payload,'{}'::jsonb),nullif(left(coalesce(p_dedupe_key,''),300),''))
  on conflict(dedupe_key) do nothing returning id into event_id;
  if event_id is not null then
    insert into public.user_notification_inbox(user_id,event_id)
    select id,event_id from public.profiles on conflict(user_id,event_id) do nothing;
  end if;
  return event_id;
end; $$;
revoke all on function public.queue_alpha_notification(text,text,text,text,jsonb,text) from public;

create or replace function public.enqueue_recommendation_publish_notification()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.is_published is not true or coalesce(new.send_push_notification,true) is not true then return new; end if;
  if tg_op='UPDATE' and coalesce(old.is_published,false)=true then return new; end if;
  perform public.queue_alpha_notification('new_recommendation','New stock recommendation: '||coalesce(new.ticker,new.company_name,'ALPHA CORE'),coalesce(new.title,new.company_name,'A new investment recommendation has been published.'),'/recommendations/'||new.id::text,jsonb_build_object('recommendation_id',new.id,'ticker',new.ticker,'company_name',new.company_name),'recommendation-published:'||new.id::text);
  return new;
end; $$;

create or replace function public.enqueue_portfolio_update_notification()
returns trigger language plpgsql security definer set search_path=public as $$
declare p record; kind text; heading text; current_alpha numeric; month_name text;
begin
  if new.is_published is not true or coalesce(new.send_push_notification,true) is not true then return new; end if;
  if tg_op='UPDATE' and new.updated_at is not distinct from old.updated_at and new.live_portfolio_return is not distinct from old.live_portfolio_return and new.live_benchmark_return is not distinct from old.live_benchmark_return and new.final_portfolio_return is not distinct from old.final_portfolio_return and new.final_benchmark_return is not distinct from old.final_benchmark_return and new.is_closed is not distinct from old.is_closed then return new; end if;
  select name,slug into p from public.portfolios where id=new.portfolio_id;
  current_alpha:=coalesce(new.live_alpha,coalesce(new.live_portfolio_return,0)-coalesce(new.live_benchmark_return,0));
  month_name:=to_char(to_date(new.month_key||'-01','YYYY-MM-DD'),'Mon YYYY');
  if tg_op='INSERT' or (tg_op='UPDATE' and coalesce(old.is_published,false)=false) then kind:='portfolio_published'; heading:='Portfolio update published';
  elsif new.live_portfolio_return is distinct from old.live_portfolio_return or new.live_benchmark_return is distinct from old.live_benchmark_return or new.final_portfolio_return is distinct from old.final_portfolio_return or new.final_benchmark_return is distinct from old.final_benchmark_return then kind:='daily_performance_update'; heading:='Daily performance updated';
  else kind:='portfolio_rebalance'; heading:='Portfolio changes published'; end if;
  perform public.queue_alpha_notification(kind,heading||': '||coalesce(p.name,'ALPHA CORE'),month_name||' is now available. Current Alpha: '||(case when current_alpha>=0 then '+' else '' end)||round(current_alpha,2)::text||'%.','/portfolio/'||coalesce(p.slug,new.portfolio_id::text),jsonb_build_object('portfolio_id',new.portfolio_id,'month_id',new.id,'month_key',new.month_key,'alpha',current_alpha),kind||':'||new.id::text||':'||to_char(coalesce(new.updated_at,now()),'YYYYMMDDHH24MISSMS'));
  return new;
end; $$;

create or replace function public.enqueue_new_portfolio_notification()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.is_published is true and coalesce(new.send_push_notification,true) is true and (tg_op='INSERT' or coalesce(old.is_published,false)=false) then
    perform public.queue_alpha_notification('new_portfolio','New portfolio launched: '||coalesce(new.name,'ALPHA CORE'),coalesce(new.description,'A new investment portfolio is now available.'),'/portfolio/'||coalesce(new.slug,new.id::text),jsonb_build_object('portfolio_id',new.id),'portfolio-launched:'||new.id::text);
  end if; return new;
end; $$;
drop trigger if exists enqueue_new_portfolio_notification on public.portfolios;
create trigger enqueue_new_portfolio_notification after insert or update on public.portfolios for each row execute function public.enqueue_new_portfolio_notification();

create or replace function public.enqueue_weekly_report_notification()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.is_published is true and coalesce(new.send_push_notification,true) is true and (tg_op='INSERT' or coalesce(old.is_published,false)=false) then
    perform public.queue_alpha_notification(case when new.slug like 'market-news-%' or new.slug like 'economic-update-%' then 'research_update' else 'weekly_report' end,coalesce(new.title,'New ALPHA CORE report'),coalesce(new.summary,'A new market update is available.'),case when new.slug like 'market-news-%' or new.slug like 'economic-update-%' then '/news/report/'||new.id::text else '/weekly-reports/'||coalesce(new.slug,new.id::text) end,jsonb_build_object('report_id',new.id),'report-published:'||new.id::text);
  end if; return new;
end; $$;
drop trigger if exists enqueue_weekly_report_notification on public.weekly_reports;
create trigger enqueue_weekly_report_notification after insert or update on public.weekly_reports for each row execute function public.enqueue_weekly_report_notification();

create or replace function public.enqueue_recommendation_update_notification()
returns trigger language plpgsql security definer set search_path=public as $$
declare r record;
begin
  if coalesce(new.send_push_notification,true) is not true then return new; end if;
  select ticker,company_name,is_published into r from public.recommendations where id=new.recommendation_id;
  if coalesce(r.is_published,false) then
    perform public.queue_alpha_notification('recommendation_update','Recommendation update: '||coalesce(r.ticker,r.company_name,'ALPHA CORE'),coalesce(new.title,'A recommendation has a new update.'),'/recommendations/'||new.recommendation_id::text,jsonb_build_object('recommendation_id',new.recommendation_id,'update_id',new.id),'recommendation-update:'||new.id::text);
  end if; return new;
end; $$;
drop trigger if exists enqueue_recommendation_update_notification on public.recommendation_updates;
create trigger enqueue_recommendation_update_notification after insert on public.recommendation_updates for each row execute function public.enqueue_recommendation_update_notification();

commit;
